# Generated by Django 5.1.6 on 2025-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='idEquipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idGrupo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
