# Generated by Django 5.1.6 on 2025-03-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_usuario_equipo_remove_usuario_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField()),
                ('Descripcion', models.TextField()),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividad', models.IntegerField()),
                ('Fecha_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idActividad', models.IntegerField()),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCalendario', models.IntegerField()),
                ('archivoTarea', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField()),
                ('idGrupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividad', models.IntegerField()),
                ('Texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPregunta', models.IntegerField()),
                ('Texto', models.TextField()),
                ('eslaCorrecta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPregunta', models.IntegerField()),
                ('idRespuesta', models.IntegerField()),
            ],
        ),
    ]
