# Generated by Django 5.1.6 on 2025-03-22 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_actividades_calendario_calificaciones_equipos_grupos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='idActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.actividades'),
        ),
    ]
