# Generated by Django 5.1.6 on 2025-03-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_calendario_idactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='idCalendario',
        ),
    ]
