# Generated by Django 5.1.6 on 2025-03-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_calificaciones_idcalendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='archivoTarea',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
