# Generated by Django 5.1.6 on 2025-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Scrum Master', 'Scrum Master'), ('Product Owner', 'Product Owner'), ('Developer 1', 'Developer 1'), ('Developer 2', 'Developer 2')], max_length=100, null=True),
        ),
    ]
