# Generated by Django 5.1.6 on 2025-05-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='idAlumno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
