# Generated by Django 5.1.6 on 2025-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notificacion_idalumno_notificacion_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='hora_limite',
            field=models.CharField(default='00', max_length=5),
        ),
    ]
