# Generated by Django 5.1.6 on 2025-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_actividades_hora_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='objetivo',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
