# Generated by Django 5.1.6 on 2025-05-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_actividades_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='id_creador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividades',
            name='id_responsable',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
