# Generated by Django 5.1.6 on 2025-05-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_actividades_id_creador_actividades_id_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='id_responsable',
        ),
        migrations.AddField(
            model_name='actividades',
            name='ro_responsable',
            field=models.CharField(default='Scrum Master', max_length=100),
        ),
    ]
