# Generated by Django 5.1.6 on 2025-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_actividades_id_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='descripcion_tarea',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
