# Generated by Django 5.1.6 on 2025-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_calificaciones_descripcion_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='extension_archivo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='nombre_archivo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
