# Generated by Django 5.1.6 on 2025-05-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_calificaciones_extension_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='ro_responsable',
            field=models.CharField(default='Maestro de Scrum', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Maestro de Scrum', 'Maestro de Scrum'), ('Propietario del Producto', 'Propietario del Producto'), ('Desarrollador 1', 'Desarrollador 1'), ('Desarrollador 2', 'Desarrollador 2')], max_length=100, null=True),
        ),
    ]
